# -*- coding: utf-8 -*-
"""Proyecto_final_parte_1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1GNDe2BvYAuS2ntxX3eDCZqwT3ZRMzMhj

## **Proyecto final parte 1: Análisis Exploratorio de Datos (EDA)**

**Realizado por:** Isabel Cristina Pérez y Anderson Taborda Hernandez

# **ANÁLISIS EXPLORATORIO DE LOS DATOS (EDA)**

##**IMPORTACIÓN DE LIBRERIAS**
"""

import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.preprocessing import MinMaxScaler, TargetEncoder
from sklearn.neural_network import MLPClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score, classification_report, f1_score, precision_score, recall_score
from sklearn.metrics import confusion_matrix, ConfusionMatrixDisplay
from sklearn.model_selection import GridSearchCV, LeaveOneOut
from sklearn.model_selection import train_test_split
from sklearn.ensemble import GradientBoostingClassifier
import xgboost as xgb
import joblib
import sys
sys.modules['sklearn.externals.joblib'] = joblib
from mlxtend.feature_selection import SequentialFeatureSelector as SFS
from keras.models import Sequential
from keras.layers import Dense, Input
from sklearn.metrics import f1_score, confusion_matrix, classification_report
from sklearn.preprocessing import StandardScaler
from imblearn.over_sampling import SMOTE

"""###**1. Carga de los Datos**"""

import kagglehub

# Download latest version
adult = kagglehub.dataset_download("wenruliu/adult-income-dataset")

print("Path to dataset files:", adult)

import shutil
import os

destination_dir = '/content/online_dataset'

# Create the destination directory if it doesn't exist
os.makedirs(destination_dir, exist_ok=True)

# Copy the contents of the source directory to the destination
# Since 'path' itself is the directory, we want to copy its contents
# to the new destination. If the destination directory already exists
# and is not empty, copytree will raise an error. So we ensure it's clean.

# First, check if the destination directory exists and remove it if it does to avoid errors
if os.path.exists(destination_dir):
    shutil.rmtree(destination_dir)

shutil.copytree(adult, destination_dir)

print(f"Files copied from {adult} to {destination_dir}")

# Now list the contents of the new directory to verify
print("Contents of the new directory:")
print(os.listdir(destination_dir))

adult_df = pd.read_csv('/content/online_dataset/adult.csv')
adult_df.info()
adult_df.head()

# 1. Diccionario de traducción
column_translation = {
    'age': 'edad',
    'workclass': 'clase_trabajo',
    'fnlwgt': 'peso_final',
    'education': 'educacion',
    'educational-num': 'educacion_num', # Ojo: a veces es con guion medio (-)
    'marital-status': 'estado_civil',
    'occupation': 'ocupacion',
    'relationship': 'relacion',
    'race': 'raza',
    'gender': 'genero',
    'capital-gain': 'ganancia_capital',
    'capital-loss': 'perdida_capital',
    'hours-per-week': 'horas_por_semana',
    'native-country': 'pais_nativo',
    'income': 'ingresos'
}

# 2. Limpiar nombres y Renombrar
adult_df.columns = adult_df.columns.str.strip()
adult_df.rename(columns=column_translation, inplace=True)

# 3. Verificar
print(adult_df.columns)
adult_df.head()

adult_df.describe()

"""###**2. Limpieza de datos**"""

adult_df.isnull().sum()

adult_df.duplicated().sum()

adult3 = adult_df.copy()

adult_2 = adult_df.drop_duplicates()

adult_2.duplicated().sum()

"""###**3. Análisis Descriptivo**"""

adult_2.describe()

adult_2['clase_trabajo'].value_counts()

adult_2.replace('?', np.nan, inplace=True)

adult_2.shape

adult_2.head()

"""El siguiente codigo se usa para determinar la cantidad se nulos encontrados en la base de datos por cada una de las variablew"""

adult_2.isnull().sum().sort_values()

"""Se determina el peso procentual de los nulos encontrado en el Database"""

adult_2.isnull().mean().sort_values(ascending=False) * 100

"""**Observación**

Se identifica que únicamente tres variables presentan valores nulos, con una proporción aproximada entre el 2 % y el 6 %. La estrategia para el tratamiento de estos datos faltantes se definirá en etapas posteriores, donde se evaluará si corresponde realizar un proceso de imputación o excluirlos del modelo.

###**4. Visualizaciones de los Datos y Graficas Univariadas y Bivariadas**
"""

import matplotlib.pyplot as plt
import seaborn as sns

# Seleccionar solo las columnas numéricas del DataFrame adult_2
numerical_cols = adult_2.select_dtypes(include=['int64', 'float64']).columns

# Determinar el número de filas y columnas para los subplots
num_numerical_cols = len(numerical_cols)
num_rows = (num_numerical_cols + 1) // 2  # Aproximadamente la mitad de columnas por fila
num_cols = 2 # Queremos 2 columnas de subplots

plt.figure(figsize=(15, 5 * num_rows))

for i, col in enumerate(numerical_cols):
    plt.subplot(num_rows, num_cols, i + 1)
    sns.histplot(adult_2[col], kde=True) # kde=True para ver la estimación de densidad del kernel
    plt.title(f'Distribución de {col}')
    plt.xlabel(col)
    plt.ylabel('Frecuencia')

plt.tight_layout()
plt.show()

import matplotlib.pyplot as plt
import seaborn as sns

# Seleccionar solo las columnas numéricas del DataFrame adult_2
numerical_cols = adult_2.select_dtypes(include=['int64', 'float64']).columns

# Determinar el número de filas y columnas para los subplots
num_numerical_cols = len(numerical_cols)
num_rows = (num_numerical_cols + 1) // 2  # Aproximadamente la mitad de columnas por fila
num_cols = 2 # Queremos 2 columnas de subplots

plt.figure(figsize=(15, 5 * num_rows))

for i, col in enumerate(numerical_cols):
    plt.subplot(num_rows, num_cols, i + 1)
    sns.boxplot(x=adult_2[col]) # Usamos 'y' para box plots verticales
    plt.title(f'Box Plot de {col}')
    plt.ylabel(col)

plt.tight_layout()
plt.show()

"""### **Análisis Bivariado**"""

import matplotlib.pyplot as plt
import seaborn as sns

plt.figure(figsize=(10, 6))
sns.boxplot(x='ingresos', y='edad', data=adult_2)
plt.title('Relación entre Edad e Ingresos')
plt.xlabel('Ingresos')
plt.ylabel('Edad')
plt.show()

import matplotlib.pyplot as plt
import seaborn as sns

plt.figure(figsize=(10, 6))
sns.boxplot(x='genero', y='edad', data=adult_2)
plt.title('Relación entre Género y Edad')
plt.xlabel('Género')
plt.ylabel('Edad')
plt.show()

sns.boxplot(x='ingresos', y='horas_por_semana', data=adult_2)
plt.show()

"""### **5. Correlaciones de la Variables**"""

cat_cols = adult_2.select_dtypes(include="object").columns
for col in cat_cols:
    print(f"\n{col}")
    print(adult_2[col].value_counts())

corr = adult_2.corr(numeric_only=True)

sns.heatmap(corr, annot=True, cmap='coolwarm')
plt.show()

"""# **6. INSIGHTS: Conclusiones del Análisis Exploratorio de Datos (EDA)**


1.  **Desequilibrio en la Variable Objetivo:** Se observa una distribución desigual en los niveles de ingresos, donde la mayoría de la población analizada percibe ingresos inferiores o iguales a 50K anuales. Esto indica que, para la fase de modelado, será necesario aplicar técnicas de balanceo (como SMOTE, ya importado en el proyecto) para evitar sesgos hacia la clase mayoritaria.

2.   **Calidad de la Información y Datos Faltantes:** A través de la inspección inicial, se identificó la presencia de valores representados por el carácter "?" en variables críticas como clase_trabajo, ocupacion y pais_nativo. La limpieza y el tratamiento de estos registros son pasos obligatorios para asegurar la integridad de los resultados en las etapas de predicción.

3.   **Relación entre Educación e Ingresos:** El análisis preliminar sugiere que el nivel educativo (representado por educacion_num) es un predictor clave. Existe una tendencia positiva donde un mayor número de años de estudio o niveles académicos superiores se asocian con una mayor probabilidad de pertenecer al segmento de ingresos superiores a 50K.

4.  **Disparidad en Variables Financieras:** Las variables ganancia_capital y perdida_capital presentan una alta concentración en valor cero para la gran mayoría de los registros. Esto sugiere que el flujo de capital por inversiones es un fenómeno presente solo en un pequeño nicho de la muestra, lo que podría requerir un tratamiento de escalado robusto o una transformación de estas variables.

5.   **Perfil Demográfico y Laboral:** La media de edad cercana a los 38 años y una jornada laboral estándar de 40 horas semanales definen el perfil predominante en el dataset. Sin embargo, la variabilidad en las horas trabajadas y la diversidad en las categorías de ocupación ofrecen una base rica para explorar segmentaciones de mercado o perfiles socioeconómicos específicos.

6.   **Preparación para el Modelado:** Basado en la naturaleza de las variables (mezcla de categóricas y numéricas), el uso de técnicas como TargetEncoder y el escalado de características (MinMaxScaler) será fundamental para normalizar las magnitudes y permitir que algoritmos de aprendizaje profundo o redes neuronales procesen la información de manera eficiente.

"""